spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/spring_order_team1
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
jwt:
  expiration: 1800000  # 30 * 60 * 1000L
  secretKey: asdfio230fj2398fdsfosewAW23jWj8381jsQs9dj1SCC0qj93djicducew092jcncNSJsjwi