apiVersion: apps/v1
kind: Deployment
metadata:
  name: jm-nginx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jm-nginx
  template:
    metadata:
      labels:
        app: jm-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80