name: deploy msa

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
          - name: checkout github
            uses: actions/checkout@v2

          - name: install kubectl
            uses: azure/setup-kubectl@v3
            with:
              version: "v1.25.9"
            id: install

          - name: configure aws
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-northeast-2

          - name: update cluster infomation
            run: aws eks update-kubeconfig --name 1team-cluster --region ap-northeast-2

          - name: Login to ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1


          - name: build and push docker item image to ecr
            env:
                REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
                REPOSITORY: team1-item
                IMAGE_TAG: latest
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            run: |
              docker build \
              -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
              -f ./order-msa-server/order-item-server/Dockerfile ./order-msa-server/order-item-server
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          - name: build and push docker member image to ecr
            env:
                REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
                REPOSITORY: team1-member
                IMAGE_TAG: latest
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            run: |
              docker build \
              -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
              -f ./order-msa-server/order-member-server/Dockerfile ./order-msa-server/order-member-server
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          - name: eks kubectl apply item
            run: |
              kubectl apply -f ./order-msa-server/order-item-server/k8s/order-item-depl-serv.yml
              kubectl rollout restart deployment jm-item-depl

          - name: eks kubectl apply member
            run: |
              kubectl apply -f ./order-msa-server/order-member-server/k8s/order-member-depl-serv.yml
              kubectl rollout restart deployment jm-member-depl 